project:
  name: asvspoof19_la_detector
  seed: 42
  device: auto

paths:
  dataset:
    root: "/Users/nasseralameri/Documents/USYD/Y4/S2/LA"
    train_audio: "ASVspoof2019_LA_train/flac"
    dev_audio:   "ASVspoof2019_LA_dev/flac"
    eval_audio:  "ASVspoof2019_LA_eval/flac"
    cm_protocols: "ASVspoof2019_LA_cm_protocols"

data:
  file_ext: ".flac"
  cm_protocol_files:
    train: "ASVspoof2019.LA.cm.train.trn.txt"
    dev:   "ASVspoof2019.LA.cm.dev.trl.txt"
    eval:  "ASVspoof2019.LA.cm.eval.trl.txt"

audio:
  sr: 16000
features:
  frame_length_ms: 25
  frame_hop_ms: 10
  lfcc:
    n_filters: 70
    n_ceps: 20
    keep_c0: true
    deltas: true
  mfcc:
    n_mels: 80
    n_ceps: 20
    keep_c0: true
    deltas: true